teams = {    
    'Max Aarons': " Bournemouth, DF",
    'Tyler Adams': "Bournemouth,MF",
    'Philip Billing': "Bournemouth,MF",
    'Ryan Christie': "Bournemouth,MF",
    'Lewis Cook': "Bournemouth,MF",
    'Romain Faivre': "Bournemouth,MF",
    'Ryan Fredericks': "Bournemouth,DF",
    'James Hill': "Bournemouth,DF",
    'Lloyd Kelly': "Bournemouth,DF",
    'Milos Kerkez': "Bournemouth,DF",
    'Maxwell Kinsey-Wellings': "Bournemouth,DF",
    'Justin Kluivert': "Bournemouth,FW",
    'Callan McKenna': "Bournemouth,GK",
    'Chris Mepham': "Bournemouth,DF",
    'Neto': "Bournemouth,GK",
    'Dango Ouattara': "Bournemouth,FW",
    'Cameron Plain': "Bournemouth,GK",
    'Ionuț Radu': "Bournemouth,GK",
    'Darren Randolph': "Bournemouth,GK",
    'Dominic Sadi': "Bournemouth,MF",
    'Alex Scott': "Bournemouth,MF",
    'Antoine Semenyo': "Bournemouth,FW",
    'Marcos Senesi': "Bournemouth,DF",
    'Luis Sinisterra': "Bournemouth,MF",
    'Adam Smith': "Bournemouth,DF",
    'Dominic Solanke': "Bournemouth,FW",
    'Marcus Tavernier': "Bournemouth,MF",
    'Mark Travers': "Bournemouth,GK",
    'Enes Ünal': "Bournemouth,FW",
    'Ilya Zabarnyi': "Bournemouth,DF",
    'Cédric': "Arsenal,DF",
    'Amario Cozier-Duberry': "Arsenal,MF",
    'David Raya': "Arsenal,GK",
    'Fábio Vieira': "Arsenal,MF",
    'Gabriel': "Arsenal,DF",
    'Gabriel Jesus': "Arsenal,FW",
    'Gabriel Martinelli': "Arsenal,FW",
    'Kai Havertz': "Arsenal,MF",
    'Karl Hein': "Arsenal,GK",
    'Jorginho': "Arsenal,MF",
    'Jakub Kiwior': "Arsenal,DF",
    'Myles Lewis-Skelly': "Arsenal,MF",
    'Mauro Bandeira': "Arsenal,MF",
    'Reiss Nelson': "Arsenal,FW",
    'Eddie Nketiah': "Arsenal,FW",
    'Ethan Nwaneri': "Arsenal,MF",
    'Martin Ødegaard': "Arsenal,MF",
    'Thomas Partey': "Arsenal,MF",
    'Aaron Ramsdale': "Arsenal,GK",
    'Declan Rice': "Arsenal,MF",
    'Bukayo Saka': "Arsenal,FW",
    'William Saliba': "Arsenal,DF",
    'Emile Smith Rowe': "Arsenal,MF",
    'James Sweet': "Arsenal,MF",
    'Jurriën Timber': "Arsenal,DF",
    'Takehiro Tomiyasu': ",Arsenal,DF",
    'Leandro Trossard': "Arsenal,FW",
    'Reuell Walters': "Arsenal,DF",
    'Ben White': "Arsenal,DF",
    'Oleksandr Zinchenko': "Arsenal,DF",
    'Álex Moreno': "Aston Villa,DF",
    'Leon Bailey': "Aston Villa,FW",
    'Emiliano Buendia': "Aston Villa,MF",
    'Matty Cash': "Aston Villa,DF",
    'Calum Chambers': "Aston Villa,DF",
    'Moussa Diaby': "Aston Villa,FW",
    'Diego Carlos': "Aston Villa,DF",
    'Lucas Digne': "Aston Villa,DF",
    'Douglas Luiz': "Aston Villa,MF",
    'Jhon Durán': "Aston Villa,FW",
    'Joe Gauci': "Aston Villa,GK",
    'Kortney Hause': "Aston Villa,DF",
    'Tim Iroegbunam': "Aston Villa,MF",
    'Boubacar Kamara': "Aston Villa,MF",
    'Omari Kellyman': "Aston Villa,FW",
    'Kaine Kesler-Hayden': "Aston Villa,DF",
    'Ezri Konsa': "Aston Villa,DF",
    'Clément Lenglet': "Aston Villa,DF",
    'Emiliano Martínez': "Aston Villa,GK",
    'John McGinn': "Aston Villa,MF",
    'Tyrone Mings': "Aston Villa,DF",
    'Finley Munroe': "Aston Villa,DF",
    'Robin Olsen': "Aston Villa,GK",
    'Pau Torres': "Aston Villa,DF",
    'Sam Proctor': "Aston Villa,GK",
    'Jacob Ramsey': "Aston Villa,MF",
    'Morgan Rogers': "Aston Villa,FW",
    'Youri Tielemans': "Aston Villa,MF",
    'Ollie Watkins': "Aston Villa,FW",
    'James Wright': "Aston Villa,GK",
    'Nicolò Zaniolo': "Aston Villa,FW",
    'Valentin Adedokun': "Brentford,FW",
    'Kristoffer Ajer': "Brentford,DF",
    'Vincent Angelini': "Brentford,GK",
    'Ellery Balcombe': "Brentford,GK",
    'Shandon Baptiste': "Brentford,MF",
    'Ethan Brierley': "Brentford,MF",
    'Nathan Collins': "Brentford,DF",
    'Mikkel Damsgaard': "Brentford,MF",
    'Joshua Dasilva': "Brentford,MF",
    'Mark Flekken': "Brentford,GK",
    'Benjamin Fredrick': "Brentford,DF",
    'Saman Ghoddos': "Brentford,FW",
    'Rico Henry': "Brentford,DF",
    'Aaron Hickey': "Brentford,DF",
    'Vitaly Janelt': "Brentford,MF",
    'Mathias Jensen': "Brentford,MF",
    'Ji-soo Kim': "Brentford,DF",
    'Yunus Konak': "Brentford,MF",
    'Keane Lewis-Potter': "Brentford,FW",
    'Neal Maupay': "Brentford,FW",
    'Bryan Mbeumo': "Brentford,FW",
    'Ben Mee': "Brentford,DF",
    'Christian Nørgaard': "Brentford,MF",
    'Frank Onyeka': "Brentford,MF",
    'Ethan Pinnock': "Brentford,DF",
    'Reguilón': "Brentford,DF",
    'Mads Roerslev': "Brentford,DF",
    'Kevin Schade': "Brentford,FW",
    'Thomas Strakosha': "Brentford,GK",
    'Ivan Toney': "Brentford,FW",
    'Ryan Trevitt': "Brentford,MF",
    'Hákon Valdimarsson': "Brentford,GK",
    'Yoane Wissa': "Brentford,FW",
    'Yegor Yarmolyuk': "Brentford,MF",
    'Zanka': "Brentford,DF",
    'Simon Adingra': "Brighton & Hove Albion,FW",
    'Ansu Fati': "Brighton & Hove Albion,FW",
    'Carlos Baleba': "Brighton & Hove Albion,MF",
    'Valentín Barco': "Brighton & Hove Albion,DF",
    'Luca Barrington': "Brighton & Hove Albion,FW",
    'Benicio Boaitey': "Brighton & Hove Albion,FW",
    'Facundo Buonanotte': "Brighton & Hove Albion,MF",
    'Samy Chouchane': "Brighton & Hove Albion,MF",
    'Joshua Duffus': "Brighton & Hove Albion,FW",
    'Lewis Dunk': "Brighton & Hove Albion,DF",
    'Julio Enciso': "Brighton & Hove Albion,FW",
    'Pervis Estupiñán': "Brighton & Hove Albion,DF",
    'Evan Ferguson': "Brighton & Hove Albion,FW",
    'Billy Gilmour': "Brighton & Hove Albion,MF",
    'Pascal Groß': "Brighton & Hove Albion,MF",
    'Jack Hinshelwood': "Brighton & Hove Albion,MF",
    'Igor': "Brighton & Hove Albion,DF",
    'Benjamin Jackson': "Brighton & Hove Albion,DF",
    'João Pedro': "Brighton & Hove Albion,FW",
    'Leigh Kavanagh': "Brighton & Hove Albion,DF",
    'Adam Lallana': "Brighton & Hove Albion,MF",
    'Tariq Lamptey': "Brighton & Hove Albion,DF",
    'Solly March': "Brighton & Hove Albion,MF",
    'Thomas McGill': "Brighton & Hove Albion,GK",
    'James Milner': "Brighton & Hove Albion,MF",
    'Kaoru Mitoma': "Brighton & Hove Albion,MF",
    'Jakub Moder': "Brighton & Hove Albion,MF",
    'Mark O\'Mahony': "Brighton & Hove Albion,FW",
    'Cameron Peupion': "Brighton & Hove Albion,MF",
    'Jason Steele': "Brighton & Hove Albion,GK",
    'Jan Paul van Hecke': "Brighton & Hove Albion,DF",
    'Joël Veltman': "Brighton & Hove Albion,DF",
    'Bart Verbruggen': "Brighton & Hove Albion,GK",
    'Caylan Vickers': "Brighton & Hove Albion,MF",
    'Adam Webster': "Brighton & Hove Albion,DF",
    'Danny Welbeck': "Brighton & Hove Albion,FW",
    'Enock Agyei': "Burnley,FW",
    'Ameen Al-Dakhil': "Burnley,DF",
    'Zeki Amdouni': "Burnley,FW",
    'Lorenz Assignon': "Burnley,DF",
    'Manuel Benson': "Burnley,FW",
    'Sander Berge': "Burnley,MF",
    'Jordan Beyer': "Burnley,DF",
    'Josh Brownhill': "Burnley,MF",
    'Jacob Bruun': "Larsen,Burnley,FW",
    'Jack Cork': "Burnley,MF",
    'Josh Cullen': "Burnley,MF",
    'Hannes Delcroix': "Burnley,DF",
    'Hjalmar Ekdal': "Burnley,DF",
    'Maxime Estève': "Burnley,DF",
    'David Fofana': "Burnley,FW",
    'Lyle Foster': "Burnley,FW",
    'Jóhann Guðmundsson': "Burnley,MF",
    'Luca Koleosho': "Burnley,FW",
    'Han-Noah Massengo': "Burnley,MF",
    'Aro Murić': "Burnley,GK",
    'Dara O\'Shea': "Burnley,DF",
    'Wilson Odobert': "Burnley,FW",
    'Aaron Ramsey': "Burnley,MF",
    'Nathan Redmond': "Burnley,FW",
    'Jay Rodriguez': "Burnley,FW",
    'Charlie Taylor': "Burnley  DF",
    'James Trafford': "Burnley,GK",
    'Mike Trésor': "Burnley,MF",
    'Lawrence Vigouroux': "Burnley,GK",
    'Vitinho': "Burnley,MF",  
    'Benoît Badiashile': "Chelsea,DF",
    'Lucas Bergström': "Chelsea,GK",
    'Marcus Bettinelli': "Chelsea,GK",
    'Joshua Brooking': "Chelsea,DF",
    'Moisés Caicedo': "Chelsea,MF",
    'Cesare Casadei': "Chelsea,MF",
    'Leo Castledine': "Chelsea,MF",
    'Trevoh Chalobah': "Chelsea,DF",
    'Ben Chilwell': "Chelsea,DF",
    'Carney Chukwuemeka': "Chelsea,MF",
    'Levi Colwill': "Chelsea,DF",
    'Cucurella': "Chelsea,DF",
    'Ted Curd': "Chelsea,GK",
    'Deivid Washington': "Chelsea,FW",
    'Diego Moreira': "Chelsea,FW",
    'Axel Disasi': "Chelsea,DF",
    'Enzo Fernández': "Chelsea,MF",
    'Wesley Fofana': "Chelsea,DF",
    'Conor Gallagher': "Chelsea,MF",
    'Alfie Gilchrist': "Chelsea,DF",
    'Michael Golding': "Chelsea,MF",
    'Malo Gusto': "Chelsea,DF",
    'Ollie Harrison': "Chelsea,MF",
    'Nicolas Jackson': "Chelsea,FW",
    'Reece James': "Chelsea,DF",
    'Roméo Lavia': "Chelsea,MF",
    'Noni Madueke': "Chelsea,FW",
    'Max Merrick': "Chelsea,GK",
    'Mykhaylo Mudryk': "Chelsea,MF",
    'Christopher Nkunku': "Chelsea,FW",
    'Cole Palmer': "Chelsea,MF",
    'Đorđe Petrović': "Chelsea,GK",
    'Robert Sánchez': "Chelsea,GK",
    'Ishé Samuels-Smith': "Chelsea,DF",
    'Malang Sarr': "Chelsea,DF",
    'Raheem Sterling': "Chelsea,FW",
    'Ronnie Stutter': "Chelsea,FW",
    'Thiago Silva': "Chelsea,DF",
    'Lesley Ugochukwu': "Chelsea,MF",
    'Dylan Williams': "Chelsea,DF",
    'Naouirou Ahamada': "Crystal Palace,MF",
    'Joachim Andersen': "Crystal Palace,DF",
    'Jordan Ayew': "Crystal Palace,FW",
    'Nathaniel Clyne': "Crystal Palace,DF",
    'Cheick Doucouré': "Crystal Palace,MF",
    'Odsonne Édouard': "Crystal Palace,FW",
    'Eberechi Eze': "Crystal Palace,MF",
    'Nathan Ferguson': "Crystal Palace,DF",
    'Marc Guéhi': "Crystal Palace,DF",
    'Dean Henderson': "Crystal Palace,GK",
    'Rob Holding': "Crystal Palace,DF",
    'Will Hughes': "Crystal Palace,MF",
    'Sam Johnstone': "Crystal Palace,GK",
    'Jefferson Lerma': "Crystal Palace,MF",
    'Jean-Philippe Mateta': "Crystal Palace,FW",
    'Matheus França': "Crystal Palace,FW",
    'Remi Matthews': "Crystal Palace,GK",
    'Tyrick Mitchell': "Crystal Palace,DF",
    'Daniel Muñoz': "Crystal Palace,DF",
    'Michael Olise': "Crystal Palace,MF",
    'David Ozoh': "Crystal Palace,MF",
    'Luke Plange': "Crystal Palace,FW",
    'Jesurun Rak-Sakyiv': "Crystal Palace,MF",
    'Jadan Raymond': "Crystal Palace,MF",
    'Chris Richards': "Crystal Palace,DF",
    'Jaïro Riedewald': "Crystal Palace,MF",
    'Jeffrey Schlupp': "Crystal Palace,MF",
    'James Tomkins': "Crystal Palace,DF",
    'Joel Ward': "Crystal Palace,DF",
    'Adam Wharton': "Crystal Palace,MF",
    'Joe Whitworth': "Crystal Palace,GK",
    'Dele Alli': "Everton,MF",
    'André Gomes': "Everton,MF",
    'Beto': "Everton,FW",
    'Jarrad Branthwaite': "Everton,DF",
    'Dominic Calvert-Lewin': "Everton,FW",
    'Séamus Coleman': "Everton,DF",
    'Arnaut Danjuma': "Everton,FW",
    'Lewis Dobbin': "Everton,FW",
    'Abdoulaye Doucouré': "Everton,MF",
    'Jammes Garner': "Everton,MF",
    'Ben Godfrey': "Everton,DF",
    'Idrissa Gueye': "Everton,MF",
    'Jack Harrison': "Everton,MF",
    'Mackenzie Hunt': "Everton,MF",
    'João Virgínia': "Everton,GK",
    'Michael Keane': "Everton,DF",
    'Andy Lonergan': "Everton,GK",
    'Dwight McNeil': "Everton,FW",
    'Jenson Metcalfe': "Everton,MF",
    'Vitaliy Mykolenko': "Everton,DF",
    'Amadou Onana': "Everton,MF",
    'Tyler Onyango': "Everton,MF",
    'Nathan Patterson': "Everton,DF",
    'Jordan Pickford': "Everton,GK",
    'James Tarkowski': "Everton,DF",
    'Ashley Young': "Everton,DF",
    'Youssef Chermiti': "Everton,FW",
    'Adama Traoré': "Fulham,FW",
    'Tosin Adarabioyo': "Fulham,DF",
    'Andreas Pereira': "Fulham,MF",
    'Fodé Ballo-Touré': "Fulham,DF",
    'Calvin Bassey': "Fulham,DF",
    'Steven Benda': "Fulham,GK",
    'Armando Broja': "Fulham,FW",
    'Tom Cairney': "Fulham,MF",
    'Timothy Castagne': "Fulham,DF",
    'Luc De Fougerolles': "Fulham,DF",
    'Bobby Decordova-Reid': "Fulham,FW",
    'Matthew Dibley-Dias': "Fulham,MF",
    'Issa Diop': "Fulham,DF",
    'Alex Iwobi': "Fulham,MF",
    'Raúl Jiménez': "Fulham,FW",
    'João Palhinha': "Fulham,MF",
    'Joshua King': "Fulham,MF",
    'Bernd Leno': "Fulham,GK",
    'Saša Lukić': "Fulham,MF",
    'Tim Ream': "Fulham,DF",
    'Harrison Reed': "Fulham,MF",
    'Antonee Robinson': "Fulham,DF",
    'Marek Rodák': "Fulham,GK",
    'Rodrigo Muniz': "Fulham,FW",
    'Kristian Šekularacv': "Fulham,MF",
    'Devan Tanton': "Fulham,DF",
    'Kenny Tete': "Fulham,DF",
    'Willian': "Fulham,FW",
    'Harry Wilson': "Fulham,FW",
    'Adrián': "Liverpool,GK",
    'Trent Alexander-Arnold': "Liverpool,DF",
    'Alisson': "Liverpool,GK",
    'Stefan Bajčetić': "Liverpool,MF",
    'Conor Bradley': "Liverpool,MF",
    'Bobby Clark': "Liverpool,MF",
    'Luis Díaz': "Liverpool,FW",
    'Diogo Jota': "Liverpool,FW",
    'Ben Doak': "Liverpool,FW",
    'Harvey Elliott': "Liverpool,MF",
    'Wataru Endo': "Liverpool,MF",
    'Cody Gakpo': "Liverpool,FW",
    'Joe Gomez': "Liverpool,DF",
    'Kaide Gordon': "Liverpool,FW",
    'Ryan Gravenberch': "Liverpool,MF",
    'Tom Hill': "Liverpool,MF",
    'Curtis Jones': "Liverpool,MF",
    'Caoimhín Kelleher': "Liverpool,GK",
    'Ibrahima Konaté': "Liverpool,DF",
    'Lewis Koumas': "Liverpool,FW",
    'Alexis Mac Allister': "Liverpool,MF",
    'Joel Matip': "Liverpool,DF",
    'James McConnell': "Liverpool,MF",
    'Fabian Mrozek': "Liverpool,GK",
    'Darwin Núñez': "Liverpool,FW",
    'Trey Nyoni': "Liverpool,MF",
    'Jarell Quansah': "Liverpool,DF",
    'Andy Robertson': "Liverpool,DF",
    'Mo Salah': "Liverpool,FW",
    'Calum Scanlon': "Liverpool,DF",
    'Dominik Szoboszlai': "Liverpool,MF",
    'Thiago': "Liverpool,MF",
    'Kostas Tsimikas': "Liverpool,DF",
    'Virgil van Dijk': "Liverpool,DF",
    'Elijah Adebayo': "Luton Town,FW",
    'Mads Andersen': "Luton Town,DF",
    'Ross Barkley': "Luton Town,MF",
    'Amari\'i Bell': "Luton Town,DF",
    'Luke Berry': "Luton Town,MF",
    'Jacob Brown': "Luton Town,FW",
    'Reece Burke': "Luton Town,DF",
    'Tahith Chong': "Luton Town,MF",
    'Jordan Clark': "Luton Town,MF",
    'Alfie Doughty': "Luton Town,MF",
    'Aiden Francis-Clarke': "Luton Town,DF",
    'Daiki Hashioka': "Luton Town,DF",
    'Joseph Johnson': "Luton Town,DF",
    'Issa Kabore': "Luton Town,DF",
    'Thomas Kaminski': "Luton Town,GK",
    'Tim Krul': "Luton Town,GK",
    'Tom Lockyer': "Luton Town,DF",
    'Albert Lokonga': "Luton Town,MF",
    'Teden Mengi': "Luton Town,DF",
    'Carlton Morris': "Luton Town,FW",
    'Pelly-Ruddock Mpanzu': "Luton Town,MF",
    'Marvelous Nakamba': "Luton Town,MF",
    'Zack Nelson': "Luton Town,MF",
    'Chiedozie Ogbene': "Luton Town,FW",
    'Fred Onyedinma': "Luton Town,MF",
    'Gabriel Osho': "Luton Town,DF",
    'Dan Potts': "Luton Town,DF",
    'James Shea': "Luton Town,GK",
    'Elliot Thorpe': "Luton Town,MF",
    'Andros Townsend': "Luton Town,FW",
    'Cauley Woodrow': "Luton Town,FW",
    'Manuel Akanji': "Manchester City,DF",
    'Nathan Aké': "Manchester City,DF",
    'Max Alleyne': "Manchester City,DF",
    'Julián Álvarez': "Manchester City,FW",
    'Bernardo Silva': "Manchester City,MF",
    'Oscar Bobb': "Manchester City,MF",
    'Scott Carson': "Manchester City,GK",
    'Kevin De Bruyne': "Manchester City,MF",
    'Jérémy Doku': "Manchester City,FW",
    'Ederson': "Manchester City,GK",
    'Phil Foden': "Manchester City,MF",
    'True Grant': "Manchester City,GK",
    'Jack Grealish': "Manchester City,MF",
    'Joško Gvardiol': "Manchester City,DF",
    'Erling Haaland': "Manchester City,FW",
    'Micah Hamilton': "Manchester City,MF",
    'Mateo Kovačić': "Manchester City,MF",
    'Rico Lewis': "Manchester City,DF",
    'Matheus Nunes': "Manchester City,MF",
    'Stefan Ortega': "Manchester City,GK",
    'Rodri': "Manchester City,MF",
    'Rúben Dias': "Manchester City,DF",
    'Sergio Gómez': "Manchester City,DF",
    'John Stones': "Manchester City,DF",
    'Mahamadou Susoho': "Manchester City,MF",
    'Kyle Walker': "Manchester City,DF",
    'Jacob Wright': "Manchester City,MF",
    'Amad': "Manchester United,MF",
    'Sofyan Amrabat': "Manchester United,MF",
    'Antony': "Manchester United,FW",
    'Altay Bayındır': "Manchester United,GK",
    'Bruno Fernandes': "Manchester United,MF",
    'Casemiro': "Manchester United,MF",
    'Diogo Dalot': "Manchester United,DF",
    'Christian Eriksen': "Manchester United,MF",
    'Jonny Evans': "Manchester United,DF",
    'Omari Forson': "Manchester United,MF",
    'Alejandro Garnacho': "Manchester United,FW",
    'Tom Heaton': "Manchester United,GK",
    'Rasmus Højlund': "Manchester United,FW",
    'Willy Kambwala': "Manchester United,DF",
    'Victor Lindelöf': "Manchester United,DF",
    'Harry Maguire': "Manchester United,DF",
    'Kobbie Mainoo': "Manchester United,MF",
    'Tyrell Malacia': "Manchester United,DF",
    'Anthony Martial': "Manchester United,FW",
    'Lisandro Martínez': "Manchester United,DF",
    'Scott McTominay': "Manchester United,MF",
    'Mason Mount': "Manchester United,MF",
    'André Onana': "Manchester United,GK",
    'Marcus Rashford': "Manchester United,FW",
    'Luke Shaw': "Manchester United,DF",
    'Shola Shoretire': "Manchester United,FW",
    'Raphaël Varane': "Manchester United,DF",
    'Aaron Wan-Bissaka': "Manchester United,DF",
    'Miguel Almirón': "Newcastle United,MF",
    'Elliot Anderson': "Newcastle United,MF",
    'Harvey Barnes': "Newcastle United,MF",
    'Sven Botman': "Newcastle United,DF",
    'Bruno Guimarães': "Newcastle United,MF",
    'Dan Burn': "Newcastle United,DF",
    'Lucas De Bolle': "Newcastle United,MF",
    'Amadou Diallo': "Newcastle United,FW",
    'Martin Dúbravka': "Newcastle United,GK",
    'Paul Dummett': "Newcastle United,DF",
    'Mark Gillespie': "Newcastle United,GK",
    'Anthony Gordon': "Newcastle United,FW",
    'Lewis Hall': "Newcastle United,MF",
    'Aidan Harris': "Newcastle United,GK",
    'Adam Harrison': "Newcastle United,GK",
    'Travis Hernes': "Newcastle United,MF",
    'James Huntley': "Newcastle United,MF",
    'Alexander Isak': "Newcastle United,FW",
    'Joelinton': "Newcastle United,MF",
    'Loris Karius': "Newcastle United,GK",
    'Emil Krafth': "Newcastle United,DF",
    'Jamaal Lascelles': "Newcastle United,DF",
    'Tino Livramento': "Newcastle United,DF",
    'Sean Longstaff': "Newcastle United,MF",
    'Lewis Miley': "Newcastle United,MF",
    'Alex Murphy': "Newcastle United,DF",
    'Jacob Murphy': "Newcastle United,MF",
    'Ben Parkinson': "Newcastle United,FW",
    'Nick Pope': "Newcastle United,GK",
    'Matt Ritchie': "Newcastle United,DF",
    'Fabian Schär': "Newcastle United,DF",
    'Matt Targett': "Newcastle United,DF",
    'Sandro Tonali': "Newcastle United,MF",
    'Kieran Trippier': "Newcastle United,DF",
    'Joe White': "Newcastle United,MF",
    'Joe Willock': "Newcastle United,MF",
    'Callum Wilson': "Newcastle United,FW",
    'Zach Abbott': "Nottingham Forest,DF",
    'Ola Aina': "Nottingham Forest,DF",
    'Harry Arter': "Nottingham Forest,MF",
    'Taiwo Awoniyi': "Nottingham Forest,FW",
    'Willy Boly': "Nottingham Forest,DF",
    'Danilo': "Nottingham Forest,MF",
    'Nicolás Domínguez': "Nottingham Forest,MF",
    'Anthony Elangav': "Nottingham Forest,FW",
    'Felipe Monteiro': "Nottingham Forest,DF",
    'Joe Gardner': "Nottingham Forest,FW",
    'Morgan Gibbs-White': "Nottingham Forest,MF",
    'Wayne Hennessey': "Nottingham Forest,GK",
    'Callum Hudson-Odoi': "Nottingham Forest,FW",
    'Cheikhou Kouyaté': "Nottingham Forest,MF",
    'Richie Laryea': "Nottingham Forest,DF",
    'Jamie McDonnell': "Nottingham Forest,MF",
    'Gonzalo Montiel': "Nottingham Forest,DF",
    'Murillo': "Nottingham Forest,DF",
    'Moussa Niakhaté': "Nottingham Forest,DF",
    'Nuno Tavares': "Nottingham Forest,DF",
    'Andrew Omobamidele': "Nottingham Forest,DF",
    'Divock Origi': "Nottingham Forest,FW",
    'Detlef Osong': "Nottingham Forest,FW",
    'Gio Reyna': "Nottingham Forest,MF",
    'Rodrigo Ribeiro': "Nottingham Forest,FW",
    'Ibrahim Sangaré': "Nottingham Forest,MF",
    'Matz Sels': "Nottingham Forest,GK",
    'Harry Toffolo': "Nottingham Forest,DF",
    'Matt Turner': "Nottingham Forest,GK",
    'Odisseas Vlachodimos': "Nottingham Forest,GK",
    'Neco Williams': "Nottingham Forest,DF",
    'Chris Wood': "Nottingham Forest,FW",
    'Ryan Yates': "Nottingham Forest,MF",
    'Anel Ahmedhodžić': "Sheffield United,DF",
    'Jordan Amissah': "Sheffield United,GK",
    'Cameron Archer': "Sheffield United,FW",
    'George Baldock': "Sheffield United,DF",
    'Chris Basham': "Sheffield United,DF",
    'Anis Ben Slimane': "Sheffield United,MF",
    'Jayden Bogle': "Sheffield United,DF",
    'Ben Brereton': "Sheffield United,FW",
    'Rhian Brewster': "Sheffield United,FW",
    'Andre Brooks': "Sheffield United,MF",
    'Adam Davies': "Sheffield United,GK",
    'Tom Davies': "Sheffield United,MF",
    'Evan Easton': "Sheffield United,DF",
    'John Egan': "Sheffield United,DF",
    'Wes Foderingham': "Sheffield United,GK",
    'Ivo Grbić': "Sheffield United,GK",
    'Gustavo Hamer': "Sheffield United,MF",
    'Mason Holgate': "Sheffield United,DF",
    'Daniel Jebbison': "Sheffield United,FW",
    'Yasser Larouci': "Sheffield United,DF",
    'Max Lowe': "Sheffield United,DF",
    'James McAtee': "Sheffield United,MF",
    'Oliver McBurnie': "Sheffield United,FW",
    'Rhys Norrington-Davies': "Sheffield United,DF",
    'Oliver Norwood': "Sheffield United,MF",
    'Ryan Oné': "Sheffield United,FW",
    'Ben Osborn': "Sheffield United,MF",
    'William Osula': "Sheffield United,FW",
    'Sydie Peck': "Sheffield United,MF",
    'Jack Robinson': "Sheffield United,DF",
    'Auston Trusty': "Sheffield United,DF",
    'Vinicius Souza': "Sheffield United,MF",
    'Brandon Austin': "Tottenham Hotspur,GK",
    'Rodrigo Bentancur': "Tottenham Hotspur,MF",
    'Yves Bissouma': "Tottenham Hotspur,MF",
    'Bryan Gil': "Tottenham Hotspur,MF",
    'Ben Davies': "Tottenham Hotspur,DF",
    'Jamie Donley': "Tottenham Hotspur,FW",
    'Alfie Dorrington': "Tottenham Hotspur,DF",
    'Radu Drăgușin': "Tottenham Hotspur,DF",
    'Emerson Royal': "Tottenham Hotspur,DF",
    'Fraser Forster': "Tottenham Hotspur,GK",
    'Pierre-Emile Højbjerg': "Tottenham Hotspur,MF",
    'Brennan Johnson': "Tottenham Hotspur,FW",
    'Dejan Kulusevski': "Tottenham Hotspur,FW",
    'Giovani Lo Celso': "Tottenham Hotspur,MF",
    'James Maddison': "Tottenham Hotspur,MF",
    'Pedro Porro': "Tottenham Hotspur,DF",
    'Richarlison': "Tottenham Hotspur,FW",
    'Cristian Romero': "Tottenham Hotspur,DF",
    'Pape Sarr': "Tottenham Hotspur,MF",
    'Dane Scarlett': "Tottenham Hotspur,FW",
    'Ryan Sessegnon': "Tottenham Hotspur,MF",
    'Oliver Skipp': "Tottenham Hotspur,MF",
    'Manor Solomon': "Tottenham Hotspur,MF",
    'Heung-min Son': "Tottenham Hotspur,FW",
    'Destiny Udogie': "Tottenham Hotspur,DF",
    'Micky van de Ven': "Tottenham Hotspur,DF",
    'Guglielmo Vicario': "Tottenham Hotspur,GK",
    'Timo Werner': "Tottenham Hotspur,FW",
    'Alfie Whiteman': "Tottenham Hotspur,GK",
    'Yago Santiago': "Tottenham Hotspur,MF",
    'Nayef Aguerd': "West Ham United,DF",
    'Edson Álvarez': "West Ham United,MF",
    'Joseph Anang': "West Ham United,GK",
    'Michail Antonio': "West Ham United,FW",
    'Alphonse Aréola': "West Ham United,GK",
    'Jarrod Bowen': "West Ham United,FW",
    'Kaelan Casey': "West Ham United,DF",
    'Maxwel Cornet': "West Ham United,MF",
    'Vladimír Coufal': "West Ham United,DF",
    'Aaron Cresswell': "West Ham United,DF",
    'Emerson': "West Ham United,DF",
    'Łukasz Fabiański': "West Ham United,GK",
    'Danny Ings': "West Ham United,FW",
    'Ben Johnson': "West Ham United,DF",
    'Mohammed Kudus': "West Ham United,FW",
    'Levi Laing': "West Ham United,MF",
    'Lucas Paquetá': "West Ham United,MF",
    'Konstantinos Mavropanos': "West Ham United,DF",
    'Divin Mubama': "West Ham United,FW",
    'Angelo Ogbonna': "West Ham United,DF",
    'Lewis Orford': "West Ham United,MF",
    'Kalvin Phillips': "West Ham United,MF",
    'Oliver Scarles': "West Ham United,MF",
    'Tomáš Souček': "West Ham United,MF",
    'James Ward-Prowse': "West Ham United,MF",
    'Kurt Zouma': "West Ham United,DF",
    'Rayan Aït Nouri': "Wolverhampton Wanderers,DF",
    'Ty Barnett': "Wolverhampton Wanderers,MF",
    'Jean Bellegarde': "Wolverhampton Wanderers,MF",
    'Daniel Bentley': "Wolverhampton Wanderers,GK",
    'Santiago Bueno': "Wolverhampton Wanderers,DF",
    'Tawanda Chirewa': "Wolverhampton Wanderers,MF",
    'Craig Dawson': "Wolverhampton Wanderers,DF",
    'Matt Doherty': "Wolverhampton Wanderers,DF",
    'Tommy Doyle': "Wolverhampton Wanderers,MF",
    'Nathan Fraser': "Wolverhampton Wanderers,FW",
    'Enso González': "Wolverhampton Wanderers,FW",
    'Harvey Griffiths': "Wolverhampton Wanderers,MF",
    'Justin Hubner': "Wolverhampton Wanderers,DF",
    'Hugo Bueno': "Wolverhampton Wanderers,DF",
    'Hee-chan Hwang': "Wolverhampton Wanderers,FW",
    'João Gomes': "Wolverhampton Wanderers,MF",
    'José Sá': "Wolverhampton Wanderers,GK",
    'Aaron Keto-Diyawa': "Wolverhampton Wanderers,DF",
    'Maximilian Kilman': "Wolverhampton Wanderers,DF",
    'Tom King': "Wolverhampton Wanderers,GK",
    'Mario Lemina': "Wolverhampton Wanderers,MF",
    'Noha Lemina': "Wolverhampton Wanderers,FW",
    'Matheus Cunha': "Wolverhampton Wanderers,FW",
    'Nélson Semedo': "Wolverhampton Wanderers,DF",
    'Pablo Sarabia': "Wolverhampton Wanderers,FW",
    'Pedro Neto': "Wolverhampton Wanderers,FW",
    'Toti': "Wolverhampton Wanderers,DF",
    'Boubacar Traoré II': "Wolverhampton Wanderers, MF",
    'Matthew Whittingham':"Wolverhampton Wanderers, DF"
}


bournemouth = {    
    'Max Aarons': " Bournemouth, DF",
    'Tyler Adams': "Bournemouth,MF",
    'Philip Billing': "Bournemouth,MF",
    'Ryan Christie': "Bournemouth,MF",
    'Lewis Cook': "Bournemouth,MF",
    'Romain Faivre': "Bournemouth,MF",
    'Ryan Fredericks': "Bournemouth,DF",
    'James Hill': "Bournemouth,DF",
    'Lloyd Kelly': "Bournemouth,DF",
    'Milos Kerkez': "Bournemouth,DF",
    'Maxwell Kinsey-Wellings': "Bournemouth,DF",
    'Justin Kluivert': "Bournemouth,FW",
    'Callan McKenna': "Bournemouth,GK",
    'Chris Mepham': "Bournemouth,DF",
    'Neto': "Bournemouth,GK",
    'Dango Ouattara': "Bournemouth,FW",
    'Cameron Plain': "Bournemouth,GK",
    'Ionuț Radu': "Bournemouth,GK",
    'Darren Randolph': "Bournemouth,GK",
    'Dominic Sadi': "Bournemouth,MF",
    'Alex Scott': "Bournemouth,MF",
    'Antoine Semenyo': "Bournemouth,FW",
    'Marcos Senesi': "Bournemouth,DF",
    'Luis Sinisterra': "Bournemouth,MF",
    'Adam Smith': "Bournemouth,DF",
    'Dominic Solanke': "Bournemouth,FW",
    'Marcus Tavernier': "Bournemouth,MF",
    'Mark Travers': "Bournemouth,GK",
    'Enes Ünal': "Bournemouth,FW",
    'Ilya Zabarnyi': "Bournemouth,DF"}

arsenal = {
    'Cédric': "Arsenal,DF",
    'Amario Cozier-Duberry': "Arsenal,MF",
    'David Raya': "Arsenal,GK",
    'Fábio Vieira': "Arsenal,MF",
    'Gabriel': "Arsenal,DF",
    'Gabriel Jesus': "Arsenal,FW",
    'Gabriel Martinelli': "Arsenal,FW",
    'Kai Havertz': "Arsenal,MF",
    'Karl Hein': "Arsenal,GK",
    'Jorginho': "Arsenal,MF",
    'Jakub Kiwior': "Arsenal,DF",
    'Myles Lewis-Skelly': "Arsenal,MF",
    'Mauro Bandeira': "Arsenal,MF",
    'Reiss Nelson': "Arsenal,FW",
    'Eddie Nketiah': "Arsenal,FW",
    'Ethan Nwaneri': "Arsenal,MF",
    'Martin Ødegaard': "Arsenal,MF",
    'Thomas Partey': "Arsenal,MF",
    'Aaron Ramsdale': "Arsenal,GK",
    'Declan Rice': "Arsenal,MF",
    'Bukayo Saka': "Arsenal,FW",
    'William Saliba': "Arsenal,DF",
    'Emile Smith Rowe': "Arsenal,MF",
    'James Sweet': "Arsenal,MF",
    'Jurriën Timber': "Arsenal,DF",
    'Takehiro Tomiyasu': ",Arsenal,DF",
    'Leandro Trossard': "Arsenal,FW",
    'Reuell Walters': "Arsenal,DF",
    'Ben White': "Arsenal,DF",
    'Oleksandr Zinchenko': "Arsenal,DF"}

aston_villa = {
    'Álex Moreno': "Aston Villa,DF",
    'Leon Bailey': "Aston Villa,FW",
    'Emiliano Buendia': "Aston Villa,MF",
    'Matty Cash': "Aston Villa,DF",
    'Calum Chambers': "Aston Villa,DF",
    'Moussa Diaby': "Aston Villa,FW",
    'Diego Carlos': "Aston Villa,DF",
    'Lucas Digne': "Aston Villa,DF",
    'Douglas Luiz': "Aston Villa,MF",
    'Jhon Durán': "Aston Villa,FW",
    'Joe Gauci': "Aston Villa,GK",
    'Kortney Hause': "Aston Villa,DF",
    'Tim Iroegbunam': "Aston Villa,MF",
    'Boubacar Kamara': "Aston Villa,MF",
    'Omari Kellyman': "Aston Villa,FW",
    'Kaine Kesler-Hayden': "Aston Villa,DF",
    'Ezri Konsa': "Aston Villa,DF",
    'Clément Lenglet': "Aston Villa,DF",
    'Emiliano Martínez': "Aston Villa,GK",
    'John McGinn': "Aston Villa,MF",
    'Tyrone Mings': "Aston Villa,DF",
    'Finley Munroe': "Aston Villa,DF",
    'Robin Olsen': "Aston Villa,GK",
    'Pau Torres': "Aston Villa,DF",
    'Sam Proctor': "Aston Villa,GK",
    'Jacob Ramsey': "Aston Villa,MF",
    'Morgan Rogers': "Aston Villa,FW",
    'Youri Tielemans': "Aston Villa,MF",
    'Ollie Watkins': "Aston Villa,FW",
    'James Wright': "Aston Villa,GK",
    'Nicolò Zaniolo': "Aston Villa,FW"}

brentford = {
    'Valentin Adedokun': "Brentford,FW",
    'Kristoffer Ajer': "Brentford,DF",
    'Vincent Angelini': "Brentford,GK",
    'Ellery Balcombe': "Brentford,GK",
    'Shandon Baptiste': "Brentford,MF",
    'Ethan Brierley': "Brentford,MF",
    'Nathan Collins': "Brentford,DF",
    'Mikkel Damsgaard': "Brentford,MF",
    'Joshua Dasilva': "Brentford,MF",
    'Mark Flekken': "Brentford,GK",
    'Benjamin Fredrick': "Brentford,DF",
    'Saman Ghoddos': "Brentford,FW",
    'Rico Henry': "Brentford,DF",
    'Aaron Hickey': "Brentford,DF",
    'Vitaly Janelt': "Brentford,MF",
    'Mathias Jensen': "Brentford,MF",
    'Ji-soo Kim': "Brentford,DF",
    'Yunus Konak': "Brentford,MF",
    'Keane Lewis-Potter': "Brentford,FW",
    'Neal Maupay': "Brentford,FW",
    'Bryan Mbeumo': "Brentford,FW",
    'Ben Mee': "Brentford,DF",
    'Christian Nørgaard': "Brentford,MF",
    'Frank Onyeka': "Brentford,MF",
    'Ethan Pinnock': "Brentford,DF",
    'Reguilón': "Brentford,DF",
    'Mads Roerslev': "Brentford,DF",
    'Kevin Schade': "Brentford,FW",
    'Thomas Strakosha': "Brentford,GK",
    'Ivan Toney': "Brentford,FW",
    'Ryan Trevitt': "Brentford,MF",
    'Hákon Valdimarsson': "Brentford,GK",
    'Yoane Wissa': "Brentford,FW",
    'Yegor Yarmolyuk': "Brentford,MF",
    'Zanka': "Brentford,DF"}

brighton = {
    'Simon Adingra': "Brighton & Hove Albion,FW",
    'Ansu Fati': "Brighton & Hove Albion,FW",
    'Carlos Baleba': "Brighton & Hove Albion,MF",
    'Valentín Barco': "Brighton & Hove Albion,DF",
    'Luca Barrington': "Brighton & Hove Albion,FW",
    'Benicio Boaitey': "Brighton & Hove Albion,FW",
    'Facundo Buonanotte': "Brighton & Hove Albion,MF",
    'Samy Chouchane': "Brighton & Hove Albion,MF",
    'Joshua Duffus': "Brighton & Hove Albion,FW",
    'Lewis Dunk': "Brighton & Hove Albion,DF",
    'Julio Enciso': "Brighton & Hove Albion,FW",
    'Pervis Estupiñán': "Brighton & Hove Albion,DF",
    'Evan Ferguson': "Brighton & Hove Albion,FW",
    'Billy Gilmour': "Brighton & Hove Albion,MF",
    'Pascal Groß': "Brighton & Hove Albion,MF",
    'Jack Hinshelwood': "Brighton & Hove Albion,MF",
    'Igor': "Brighton & Hove Albion,DF",
    'Benjamin Jackson': "Brighton & Hove Albion,DF",
    'João Pedro': "Brighton & Hove Albion,FW",
    'Leigh Kavanagh': "Brighton & Hove Albion,DF",
    'Adam Lallana': "Brighton & Hove Albion,MF",
    'Tariq Lamptey': "Brighton & Hove Albion,DF",
    'Solly March': "Brighton & Hove Albion,MF",
    'Thomas McGill': "Brighton & Hove Albion,GK",
    'James Milner': "Brighton & Hove Albion,MF",
    'Kaoru Mitoma': "Brighton & Hove Albion,MF",
    'Jakub Moder': "Brighton & Hove Albion,MF",
    'Mark O\'Mahony': "Brighton & Hove Albion,FW",
    'Cameron Peupion': "Brighton & Hove Albion,MF",
    'Jason Steele': "Brighton & Hove Albion,GK",
    'Jan Paul van Hecke': "Brighton & Hove Albion,DF",
    'Joël Veltman': "Brighton & Hove Albion,DF",
    'Bart Verbruggen': "Brighton & Hove Albion,GK",
    'Caylan Vickers': "Brighton & Hove Albion,MF",
    'Adam Webster': "Brighton & Hove Albion,DF",
    'Danny Welbeck': "Brighton & Hove Albion,FW"}

burnley = {
    'Enock Agyei': "Burnley,FW",
    'Ameen Al-Dakhil': "Burnley,DF",
    'Zeki Amdouni': "Burnley,FW",
    'Lorenz Assignon': "Burnley,DF",
    'Manuel Benson': "Burnley,FW",
    'Sander Berge': "Burnley,MF",
    'Jordan Beyer': "Burnley,DF",
    'Josh Brownhill': "Burnley,MF",
    'Jacob Bruun': "Larsen,Burnley,FW",
    'Jack Cork': "Burnley,MF",
    'Josh Cullen': "Burnley,MF",
    'Hannes Delcroix': "Burnley,DF",
    'Hjalmar Ekdal': "Burnley,DF",
    'Maxime Estève': "Burnley,DF",
    'David Fofana': "Burnley,FW",
    'Lyle Foster': "Burnley,FW",
    'Jóhann Guðmundsson': "Burnley,MF",
    'Luca Koleosho': "Burnley,FW",
    'Han-Noah Massengo': "Burnley,MF",
    'Aro Murić': "Burnley,GK",
    'Dara O\'Shea': "Burnley,DF",
    'Wilson Odobert': "Burnley,FW",
    'Aaron Ramsey': "Burnley,MF",
    'Nathan Redmond': "Burnley,FW",
    'Jay Rodriguez': "Burnley,FW",
    'Charlie Taylor': "Burnley  DF",
    'James Trafford': "Burnley,GK",
    'Mike Trésor': "Burnley,MF",
    'Lawrence Vigouroux': "Burnley,GK",
    'Vitinho': "Burnley,MF"}

chelsea = {   
    'Benoît Badiashile': "Chelsea,DF",
    'Lucas Bergström': "Chelsea,GK",
    'Marcus Bettinelli': "Chelsea,GK",
    'Joshua Brooking': "Chelsea,DF",
    'Moisés Caicedo': "Chelsea,MF",
    'Cesare Casadei': "Chelsea,MF",
    'Leo Castledine': "Chelsea,MF",
    'Trevoh Chalobah': "Chelsea,DF",
    'Ben Chilwell': "Chelsea,DF",
    'Carney Chukwuemeka': "Chelsea,MF",
    'Levi Colwill': "Chelsea,DF",
    'Cucurella': "Chelsea,DF",
    'Ted Curd': "Chelsea,GK",
    'Deivid Washington': "Chelsea,FW",
    'Diego Moreira': "Chelsea,FW",
    'Axel Disasi': "Chelsea,DF",
    'Enzo Fernández': "Chelsea,MF",
    'Wesley Fofana': "Chelsea,DF",
    'Conor Gallagher': "Chelsea,MF",
    'Alfie Gilchrist': "Chelsea,DF",
    'Michael Golding': "Chelsea,MF",
    'Malo Gusto': "Chelsea,DF",
    'Ollie Harrison': "Chelsea,MF",
    'Nicolas Jackson': "Chelsea,FW",
    'Reece James': "Chelsea,DF",
    'Roméo Lavia': "Chelsea,MF",
    'Noni Madueke': "Chelsea,FW",
    'Max Merrick': "Chelsea,GK",
    'Mykhaylo Mudryk': "Chelsea,MF",
    'Christopher Nkunku': "Chelsea,FW",
    'Cole Palmer': "Chelsea,MF",
    'Đorđe Petrović': "Chelsea,GK",
    'Robert Sánchez': "Chelsea,GK",
    'Ishé Samuels-Smith': "Chelsea,DF",
    'Malang Sarr': "Chelsea,DF",
    'Raheem Sterling': "Chelsea,FW",
    'Ronnie Stutter': "Chelsea,FW",
    'Thiago Silva': "Chelsea,DF",
    'Lesley Ugochukwu': "Chelsea,MF",
    'Dylan Williams': "Chelsea,DF"}


crystal_palace = {
    'Naouirou Ahamada': "Crystal Palace,MF",
    'Joachim Andersen': "Crystal Palace,DF",
    'Jordan Ayew': "Crystal Palace,FW",
    'Nathaniel Clyne': "Crystal Palace,DF",
    'Cheick Doucouré': "Crystal Palace,MF",
    'Odsonne Édouard': "Crystal Palace,FW",
    'Eberechi Eze': "Crystal Palace,MF",
    'Nathan Ferguson': "Crystal Palace,DF",
    'Marc Guéhi': "Crystal Palace,DF",
    'Dean Henderson': "Crystal Palace,GK",
    'Rob Holding': "Crystal Palace,DF",
    'Will Hughes': "Crystal Palace,MF",
    'Sam Johnstone': "Crystal Palace,GK",
    'Jefferson Lerma': "Crystal Palace,MF",
    'Jean-Philippe Mateta': "Crystal Palace,FW",
    'Matheus França': "Crystal Palace,FW",
    'Remi Matthews': "Crystal Palace,GK",
    'Tyrick Mitchell': "Crystal Palace,DF",
    'Daniel Muñoz': "Crystal Palace,DF",
    'Michael Olise': "Crystal Palace,MF",
    'David Ozoh': "Crystal Palace,MF",
    'Luke Plange': "Crystal Palace,FW",
    'Jesurun Rak-Sakyiv': "Crystal Palace,MF",
    'Jadan Raymond': "Crystal Palace,MF",
    'Chris Richards': "Crystal Palace,DF",
    'Jaïro Riedewald': "Crystal Palace,MF",
    'Jeffrey Schlupp': "Crystal Palace,MF",
    'James Tomkins': "Crystal Palace,DF",
    'Joel Ward': "Crystal Palace,DF",
    'Adam Wharton': "Crystal Palace,MF",
    'Joe Whitworth': "Crystal Palace,GK"}

everton = {
    'Dele Alli': "Everton,MF",
    'André Gomes': "Everton,MF",
    'Beto': "Everton,FW",
    'Jarrad Branthwaite': "Everton,DF",
    'Dominic Calvert-Lewin': "Everton,FW",
    'Séamus Coleman': "Everton,DF",
    'Arnaut Danjuma': "Everton,FW",
    'Lewis Dobbin': "Everton,FW",
    'Abdoulaye Doucouré': "Everton,MF",
    'Jammes Garner': "Everton,MF",
    'Ben Godfrey': "Everton,DF",
    'Idrissa Gueye': "Everton,MF",
    'Jack Harrison': "Everton,MF",
    'Mackenzie Hunt': "Everton,MF",
    'João Virgínia': "Everton,GK",
    'Michael Keane': "Everton,DF",
    'Andy Lonergan': "Everton,GK",
    'Dwight McNeil': "Everton,FW",
    'Jenson Metcalfe': "Everton,MF",
    'Vitaliy Mykolenko': "Everton,DF",
    'Amadou Onana': "Everton,MF",
    'Tyler Onyango': "Everton,MF",
    'Nathan Patterson': "Everton,DF",
    'Jordan Pickford': "Everton,GK",
    'James Tarkowski': "Everton,DF",
    'Ashley Young': "Everton,DF",
    'Youssef Chermiti': "Everton,FW"}


fulham = {
    'Adama Traoré': "Fulham,FW",
    'Tosin Adarabioyo': "Fulham,DF",
    'Andreas Pereira': "Fulham,MF",
    'Fodé Ballo-Touré': "Fulham,DF",
    'Calvin Bassey': "Fulham,DF",
    'Steven Benda': "Fulham,GK",
    'Armando Broja': "Fulham,FW",
    'Tom Cairney': "Fulham,MF",
    'Timothy Castagne': "Fulham,DF",
    'Luc De Fougerolles': "Fulham,DF",
    'Bobby Decordova-Reid': "Fulham,FW",
    'Matthew Dibley-Dias': "Fulham,MF",
    'Issa Diop': "Fulham,DF",
    'Alex Iwobi': "Fulham,MF",
    'Raúl Jiménez': "Fulham,FW",
    'João Palhinha': "Fulham,MF",
    'Joshua King': "Fulham,MF",
    'Bernd Leno': "Fulham,GK",
    'Saša Lukić': "Fulham,MF",
    'Tim Ream': "Fulham,DF",
    'Harrison Reed': "Fulham,MF",
    'Antonee Robinson': "Fulham,DF",
    'Marek Rodák': "Fulham,GK",
    'Rodrigo Muniz': "Fulham,FW",
    'Kristian Šekularacv': "Fulham,MF",
    'Devan Tanton': "Fulham,DF",
    'Kenny Tete': "Fulham,DF",
    'Willian': "Fulham,FW",
    'Harry Wilson': "Fulham,FW"}

liverpool = {
    'Adrián': "Liverpool,GK",
    'Trent Alexander-Arnold': "Liverpool,DF",
    'Alisson': "Liverpool,GK",
    'Stefan Bajčetić': "Liverpool,MF",
    'Conor Bradley': "Liverpool,MF",
    'Bobby Clark': "Liverpool,MF",
    'Luis Díaz': "Liverpool,FW",
    'Diogo Jota': "Liverpool,FW",
    'Ben Doak': "Liverpool,FW",
    'Harvey Elliott': "Liverpool,MF",
    'Wataru Endo': "Liverpool,MF",
    'Cody Gakpo': "Liverpool,FW",
    'Joe Gomez': "Liverpool,DF",
    'Kaide Gordon': "Liverpool,FW",
    'Ryan Gravenberch': "Liverpool,MF",
    'Tom Hill': "Liverpool,MF",
    'Curtis Jones': "Liverpool,MF",
    'Caoimhín Kelleher': "Liverpool,GK",
    'Ibrahima Konaté': "Liverpool,DF",
    'Lewis Koumas': "Liverpool,FW",
    'Alexis Mac Allister': "Liverpool,MF",
    'Joel Matip': "Liverpool,DF",
    'James McConnell': "Liverpool,MF",
    'Fabian Mrozek': "Liverpool,GK",
    'Darwin Núñez': "Liverpool,FW",
    'Trey Nyoni': "Liverpool,MF",
    'Jarell Quansah': "Liverpool,DF",
    'Andy Robertson': "Liverpool,DF",
    'Mo Salah': "Liverpool,FW",
    'Calum Scanlon': "Liverpool,DF",
    'Dominik Szoboszlai': "Liverpool,MF",
    'Thiago': "Liverpool,MF",
    'Kostas Tsimikas': "Liverpool,DF",
    'Virgil van Dijk': "Liverpool,DF"}

luton = {
    'Elijah Adebayo': "Luton Town,FW",
    'Mads Andersen': "Luton Town,DF",
    'Ross Barkley': "Luton Town,MF",
    'Amari\'i Bell': "Luton Town,DF",
    'Luke Berry': "Luton Town,MF",
    'Jacob Brown': "Luton Town,FW",
    'Reece Burke': "Luton Town,DF",
    'Tahith Chong': "Luton Town,MF",
    'Jordan Clark': "Luton Town,MF",
    'Alfie Doughty': "Luton Town,MF",
    'Aiden Francis-Clarke': "Luton Town,DF",
    'Daiki Hashioka': "Luton Town,DF",
    'Joseph Johnson': "Luton Town,DF",
    'Issa Kabore': "Luton Town,DF",
    'Thomas Kaminski': "Luton Town,GK",
    'Tim Krul': "Luton Town,GK",
    'Tom Lockyer': "Luton Town,DF",
    'Albert Lokonga': "Luton Town,MF",
    'Teden Mengi': "Luton Town,DF",
    'Carlton Morris': "Luton Town,FW",
    'Pelly-Ruddock Mpanzu': "Luton Town,MF",
    'Marvelous Nakamba': "Luton Town,MF",
    'Zack Nelson': "Luton Town,MF",
    'Chiedozie Ogbene': "Luton Town,FW",
    'Fred Onyedinma': "Luton Town,MF",
    'Gabriel Osho': "Luton Town,DF",
    'Dan Potts': "Luton Town,DF",
    'James Shea': "Luton Town,GK",
    'Elliot Thorpe': "Luton Town,MF",
    'Andros Townsend': "Luton Town,FW",
    'Cauley Woodrow': "Luton Town,FW"}

manchester_city = {
    'Manuel Akanji': "Manchester City,DF",
    'Nathan Aké': "Manchester City,DF",
    'Max Alleyne': "Manchester City,DF",
    'Julián Álvarez': "Manchester City,FW",
    'Bernardo Silva': "Manchester City,MF",
    'Oscar Bobb': "Manchester City,MF",
    'Scott Carson': "Manchester City,GK",
    'Kevin De Bruyne': "Manchester City,MF",
    'Jérémy Doku': "Manchester City,FW",
    'Ederson': "Manchester City,GK",
    'Phil Foden': "Manchester City,MF",
    'True Grant': "Manchester City,GK",
    'Jack Grealish': "Manchester City,MF",
    'Joško Gvardiol': "Manchester City,DF",
    'Erling Haaland': "Manchester City,FW",
    'Micah Hamilton': "Manchester City,MF",
    'Mateo Kovačić': "Manchester City,MF",
    'Rico Lewis': "Manchester City,DF",
    'Matheus Nunes': "Manchester City,MF",
    'Stefan Ortega': "Manchester City,GK",
    'Rodri': "Manchester City,MF",
    'Rúben Dias': "Manchester City,DF",
    'Sergio Gómez': "Manchester City,DF",
    'John Stones': "Manchester City,DF",
    'Mahamadou Susoho': "Manchester City,MF",
    'Kyle Walker': "Manchester City,DF",
    'Jacob Wright': "Manchester City,MF"}

manchester_united = {
    'Amad': "Manchester United,MF",
    'Sofyan Amrabat': "Manchester United,MF",
    'Antony': "Manchester United,FW",
    'Altay Bayındır': "Manchester United,GK",
    'Bruno Fernandes': "Manchester United,MF",
    'Casemiro': "Manchester United,MF",
    'Diogo Dalot': "Manchester United,DF",
    'Christian Eriksen': "Manchester United,MF",
    'Jonny Evans': "Manchester United,DF",
    'Omari Forson': "Manchester United,MF",
    'Alejandro Garnacho': "Manchester United,FW",
    'Tom Heaton': "Manchester United,GK",
    'Rasmus Højlund': "Manchester United,FW",
    'Willy Kambwala': "Manchester United,DF",
    'Victor Lindelöf': "Manchester United,DF",
    'Harry Maguire': "Manchester United,DF",
    'Kobbie Mainoo': "Manchester United,MF",
    'Tyrell Malacia': "Manchester United,DF",
    'Anthony Martial': "Manchester United,FW",
    'Lisandro Martínez': "Manchester United,DF",
    'Scott McTominay': "Manchester United,MF",
    'Mason Mount': "Manchester United,MF",
    'André Onana': "Manchester United,GK",
    'Marcus Rashford': "Manchester United,FW",
    'Luke Shaw': "Manchester United,DF",
    'Shola Shoretire': "Manchester United,FW",
    'Raphaël Varane': "Manchester United,DF",
    'Aaron Wan-Bissaka': "Manchester United,DF"}

newcastle = {
    'Miguel Almirón': "Newcastle United,MF",
    'Elliot Anderson': "Newcastle United,MF",
    'Harvey Barnes': "Newcastle United,MF",
    'Sven Botman': "Newcastle United,DF",
    'Bruno Guimarães': "Newcastle United,MF",
    'Dan Burn': "Newcastle United,DF",
    'Lucas De Bolle': "Newcastle United,MF",
    'Amadou Diallo': "Newcastle United,FW",
    'Martin Dúbravka': "Newcastle United,GK",
    'Paul Dummett': "Newcastle United,DF",
    'Mark Gillespie': "Newcastle United,GK",
    'Anthony Gordon': "Newcastle United,FW",
    'Lewis Hall': "Newcastle United,MF",
    'Aidan Harris': "Newcastle United,GK",
    'Adam Harrison': "Newcastle United,GK",
    'Travis Hernes': "Newcastle United,MF",
    'James Huntley': "Newcastle United,MF",
    'Alexander Isak': "Newcastle United,FW",
    'Joelinton': "Newcastle United,MF",
    'Loris Karius': "Newcastle United,GK",
    'Emil Krafth': "Newcastle United,DF",
    'Jamaal Lascelles': "Newcastle United,DF",
    'Tino Livramento': "Newcastle United,DF",
    'Sean Longstaff': "Newcastle United,MF",
    'Lewis Miley': "Newcastle United,MF",
    'Alex Murphy': "Newcastle United,DF",
    'Jacob Murphy': "Newcastle United,MF",
    'Ben Parkinson': "Newcastle United,FW",
    'Nick Pope': "Newcastle United,GK",
    'Matt Ritchie': "Newcastle United,DF",
    'Fabian Schär': "Newcastle United,DF",
    'Matt Targett': "Newcastle United,DF",
    'Sandro Tonali': "Newcastle United,MF",
    'Kieran Trippier': "Newcastle United,DF",
    'Joe White': "Newcastle United,MF",
    'Joe Willock': "Newcastle United,MF",
    'Callum Wilson': "Newcastle United,FW"}

nottingham_forest = {
    'Zach Abbott': "Nottingham Forest,DF",
    'Ola Aina': "Nottingham Forest,DF",
    'Harry Arter': "Nottingham Forest,MF",
    'Taiwo Awoniyi': "Nottingham Forest,FW",
    'Willy Boly': "Nottingham Forest,DF",
    'Danilo': "Nottingham Forest,MF",
    'Nicolás Domínguez': "Nottingham Forest,MF",
    'Anthony Elangav': "Nottingham Forest,FW",
    'Felipe Monteiro': "Nottingham Forest,DF",
    'Joe Gardner': "Nottingham Forest,FW",
    'Morgan Gibbs-White': "Nottingham Forest,MF",
    'Wayne Hennessey': "Nottingham Forest,GK",
    'Callum Hudson-Odoi': "Nottingham Forest,FW",
    'Cheikhou Kouyaté': "Nottingham Forest,MF",
    'Richie Laryea': "Nottingham Forest,DF",
    'Jamie McDonnell': "Nottingham Forest,MF",
    'Gonzalo Montiel': "Nottingham Forest,DF",
    'Murillo': "Nottingham Forest,DF",
    'Moussa Niakhaté': "Nottingham Forest,DF",
    'Nuno Tavares': "Nottingham Forest,DF",
    'Andrew Omobamidele': "Nottingham Forest,DF",
    'Divock Origi': "Nottingham Forest,FW",
    'Detlef Osong': "Nottingham Forest,FW",
    'Gio Reyna': "Nottingham Forest,MF",
    'Rodrigo Ribeiro': "Nottingham Forest,FW",
    'Ibrahim Sangaré': "Nottingham Forest,MF",
    'Matz Sels': "Nottingham Forest,GK",
    'Harry Toffolo': "Nottingham Forest,DF",
    'Matt Turner': "Nottingham Forest,GK",
    'Odisseas Vlachodimos': "Nottingham Forest,GK",
    'Neco Williams': "Nottingham Forest,DF",
    'Chris Wood': "Nottingham Forest,FW",
    'Ryan Yates': "Nottingham Forest,MF"}

sheffoeld_united = {
    'Anel Ahmedhodžić': "Sheffield United,DF",
    'Jordan Amissah': "Sheffield United,GK",
    'Cameron Archer': "Sheffield United,FW",
    'George Baldock': "Sheffield United,DF",
    'Chris Basham': "Sheffield United,DF",
    'Anis Ben Slimane': "Sheffield United,MF",
    'Jayden Bogle': "Sheffield United,DF",
    'Ben Brereton': "Sheffield United,FW",
    'Rhian Brewster': "Sheffield United,FW",
    'Andre Brooks': "Sheffield United,MF",
    'Adam Davies': "Sheffield United,GK",
    'Tom Davies': "Sheffield United,MF",
    'Evan Easton': "Sheffield United,DF",
    'John Egan': "Sheffield United,DF",
    'Wes Foderingham': "Sheffield United,GK",
    'Ivo Grbić': "Sheffield United,GK",
    'Gustavo Hamer': "Sheffield United,MF",
    'Mason Holgate': "Sheffield United,DF",
    'Daniel Jebbison': "Sheffield United,FW",
    'Yasser Larouci': "Sheffield United,DF",
    'Max Lowe': "Sheffield United,DF",
    'James McAtee': "Sheffield United,MF",
    'Oliver McBurnie': "Sheffield United,FW",
    'Rhys Norrington-Davies': "Sheffield United,DF",
    'Oliver Norwood': "Sheffield United,MF",
    'Ryan Oné': "Sheffield United,FW",
    'Ben Osborn': "Sheffield United,MF",
    'William Osula': "Sheffield United,FW",
    'Sydie Peck': "Sheffield United,MF",
    'Jack Robinson': "Sheffield United,DF",
    'Auston Trusty': "Sheffield United,DF",
    'Vinicius Souza': "Sheffield United,MF"}

tottenham = {
    'Brandon Austin': "Tottenham Hotspur,GK",
    'Rodrigo Bentancur': "Tottenham Hotspur,MF",
    'Yves Bissouma': "Tottenham Hotspur,MF",
    'Bryan Gil': "Tottenham Hotspur,MF",
    'Ben Davies': "Tottenham Hotspur,DF",
    'Jamie Donley': "Tottenham Hotspur,FW",
    'Alfie Dorrington': "Tottenham Hotspur,DF",
    'Radu Drăgușin': "Tottenham Hotspur,DF",
    'Emerson Royal': "Tottenham Hotspur,DF",
    'Fraser Forster': "Tottenham Hotspur,GK",
    'Pierre-Emile Højbjerg': "Tottenham Hotspur,MF",
    'Brennan Johnson': "Tottenham Hotspur,FW",
    'Dejan Kulusevski': "Tottenham Hotspur,FW",
    'Giovani Lo Celso': "Tottenham Hotspur,MF",
    'James Maddison': "Tottenham Hotspur,MF",
    'Pedro Porro': "Tottenham Hotspur,DF",
    'Richarlison': "Tottenham Hotspur,FW",
    'Cristian Romero': "Tottenham Hotspur,DF",
    'Pape Sarr': "Tottenham Hotspur,MF",
    'Dane Scarlett': "Tottenham Hotspur,FW",
    'Ryan Sessegnon': "Tottenham Hotspur,MF",
    'Oliver Skipp': "Tottenham Hotspur,MF",
    'Manor Solomon': "Tottenham Hotspur,MF",
    'Heung-min Son': "Tottenham Hotspur,FW",
    'Destiny Udogie': "Tottenham Hotspur,DF",
    'Micky van de Ven': "Tottenham Hotspur,DF",
    'Guglielmo Vicario': "Tottenham Hotspur,GK",
    'Timo Werner': "Tottenham Hotspur,FW",
    'Alfie Whiteman': "Tottenham Hotspur,GK",
    'Yago Santiago': "Tottenham Hotspur,MF"}

west_ham = {
    'Nayef Aguerd': "West Ham United,DF",
    'Edson Álvarez': "West Ham United,MF",
    'Joseph Anang': "West Ham United,GK",
    'Michail Antonio': "West Ham United,FW",
    'Alphonse Aréola': "West Ham United,GK",
    'Jarrod Bowen': "West Ham United,FW",
    'Kaelan Casey': "West Ham United,DF",
    'Maxwel Cornet': "West Ham United,MF",
    'Vladimír Coufal': "West Ham United,DF",
    'Aaron Cresswell': "West Ham United,DF",
    'Emerson': "West Ham United,DF",
    'Łukasz Fabiański': "West Ham United,GK",
    'Danny Ings': "West Ham United,FW",
    'Ben Johnson': "West Ham United,DF",
    'Mohammed Kudus': "West Ham United,FW",
    'Levi Laing': "West Ham United,MF",
    'Lucas Paquetá': "West Ham United,MF",
    'Konstantinos Mavropanos': "West Ham United,DF",
    'Divin Mubama': "West Ham United,FW",
    'Angelo Ogbonna': "West Ham United,DF",
    'Lewis Orford': "West Ham United,MF",
    'Kalvin Phillips': "West Ham United,MF",
    'Oliver Scarles': "West Ham United,MF",
    'Tomáš Souček': "West Ham United,MF",
    'James Ward-Prowse': "West Ham United,MF",
    'Kurt Zouma': "West Ham United,DF"}

wolverhampton = { 
    'Rayan Aït Nouri': "Wolverhampton Wanderers,DF",
    'Ty Barnett': "Wolverhampton Wanderers,MF",
    'Jean Bellegarde': "Wolverhampton Wanderers,MF",
    'Daniel Bentley': "Wolverhampton Wanderers,GK",
    'Santiago Bueno': "Wolverhampton Wanderers,DF",
    'Tawanda Chirewa': "Wolverhampton Wanderers,MF",
    'Craig Dawson': "Wolverhampton Wanderers,DF",
    'Matt Doherty': "Wolverhampton Wanderers,DF",
    'Tommy Doyle': "Wolverhampton Wanderers,MF",
    'Nathan Fraser': "Wolverhampton Wanderers,FW",
    'Enso González': "Wolverhampton Wanderers,FW",
    'Harvey Griffiths': "Wolverhampton Wanderers,MF",
    'Justin Hubner': "Wolverhampton Wanderers,DF",
    'Hugo Bueno': "Wolverhampton Wanderers,DF",
    'Hee-chan Hwang': "Wolverhampton Wanderers,FW",
    'João Gomes': "Wolverhampton Wanderers,MF",
    'José Sá': "Wolverhampton Wanderers,GK",
    'Aaron Keto-Diyawa': "Wolverhampton Wanderers,DF",
    'Maximilian Kilman': "Wolverhampton Wanderers,DF",
    'Tom King': "Wolverhampton Wanderers,GK",
    'Mario Lemina': "Wolverhampton Wanderers,MF",
    'Noha Lemina': "Wolverhampton Wanderers,FW",
    'Matheus Cunha': "Wolverhampton Wanderers,FW",
    'Nélson Semedo': "Wolverhampton Wanderers,DF",
    'Pablo Sarabia': "Wolverhampton Wanderers,FW",
    'Pedro Neto': "Wolverhampton Wanderers,FW",
    'Toti': "Wolverhampton Wanderers,DF",
    'Boubacar Traoré II': "Wolverhampton Wanderers, MF",
    'Matthew Whittingham':"Wolverhampton Wanderers, DF"
}